language: scala
scala:
- 2.12.1
jdk: oraclejdk8
env:
  global:
  - SBT_VERSION=0.13.13
before_script:
- export BEFORE_SCRIPT_START="$(date +%s)"
- export BUILD_START="$(ls -l --time-style=+%s -d /proc/1 | awk '{print $6}')"
- mkdir -p $HOME/.sbt/launchers/$SBT_VERSION/
- curl -L -o $HOME/.sbt/launchers/$SBT_VERSION/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$SBT_VERSION/sbt-launch.jar
- java -version
script: bash bin/travis
after_script:
- AFTER_SCRIPT_START="$(date +%s)" && echo "Build end:           $AFTER_SCRIPT_START"
dist: trusty
sudo: false
notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK_URL
    on_success: change
    on_failure: always
    on_start: never
