language: scala
scala:
- 2.12.1
jdk: oraclejdk8
env:
  global:
  - SBT_VERSION=0.13.13
before_script:
- mkdir -p $HOME/.sbt/launchers/$SBT_VERSION/
- curl -L -o $HOME/.sbt/launchers/$SBT_VERSION/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$SBT_VERSION/sbt-launch.jar
- java -version
script: bash bin/travis
sudo: false
notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK_URL
    on_success: change
    on_failure: always
    on_start: never
